# Generated by Django 4.0.6 on 2022-08-09 12:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userid', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('userType', models.CharField(choices=[('Student', 'Student'), ('Instructor', 'Instructor'), ('Admin', 'Admin')], max_length=10)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('desc', models.CharField(max_length=100)),
                ('course_credits', models.FloatField()),
                ('department', models.CharField(choices=[('AM', 'Engineering and Computational Mechanics'), ('BB', 'Biochemical Engineering and Biotechnology'), ('CH', 'Chemical Engineering'), ('CS', 'Computer Science and Engineering'), ('CE', 'Civil Engineering'), ('EE', 'Electrical Engineering'), ('ES', 'Energy Science and Engineering'), ('MS', 'Materials Science and Engineering'), ('MT', 'Mathematics'), ('ME', 'Mechanical Engineering'), ('PH', 'Physics'), ('TT', 'Textile and Fibre Engineering')], max_length=100)),
                ('course_intro', models.FileField(upload_to='course_intro')),
                ('publish_grades', models.BooleanField(default=False)),
                ('profs', models.ManyToManyField(related_name='course_profs', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(related_name='course_students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
