# Generated by Django 4.0.6 on 2022-08-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='icon',
            field=models.ImageField(default='course-icons/default.jpg', upload_to='course-icons'),
        ),
    ]
