# Generated by Django 4.0.6 on 2022-08-13 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_course_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_intro',
        ),
    ]
