# Generated by Django 4.0.6 on 2022-08-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_alter_grade_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='marks',
        ),
        migrations.AddField(
            model_name='score',
            name='student_score',
            field=models.FloatField(default=0, help_text="student's score"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='score',
            name='total_score',
            field=models.FloatField(help_text='maximum score'),
        ),
    ]
