# Generated by Django 4.0.6 on 2022-08-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_assignment_resubmissions_allowed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='name',
            field=models.CharField(help_text='Enter display name', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.CharField(help_text='Enter display name', max_length=200),
        ),
        migrations.AlterField(
            model_name='submission',
            name='name',
            field=models.CharField(help_text='Enter display name', max_length=200),
        ),
    ]
